python crop_hdtf.py \
    --workers 1 \
    --device_ids 0 \
    --format .mp4 \
    --chunks_metadata debug.csv \
    --image_shape 512,512 \
    --in_folder ../example_dataset \
    --out_folder debug_output \
    --increase 0.1
     
# remove the csv file generated by the previous command
rm -f debug.csv 

# repeat with 0.2, in order to get a greater region of interest if possible
python crop_hdtf.py \
    --workers 1 \
    --device_ids 0 \
    --format .mp4 \
    --chunks_metadata debug.csv \
    --image_shape 512,512 \
    --in_folder ../example_dataset \
    --out_folder debug_output \
    --increase 0.2

rm -rf debug.csv